import Foundation

/// The tool-schema declarations the model sees — extracted from `ToolAgent` so the orchestration
/// logic (the tool-calling loop, planning, compaction) and the large schema catalogue live apart.
/// Built fresh each call (a static `[String: Any]` isn't Sendable in Swift 6). The handlers these
/// schemas describe live in the focused ToolAgent*Tools.swift files, dispatched by `handleTool`.
extension ToolAgent {
    // Tools are built fresh each call — a static `[String: Any]` isn't Sendable in Swift 6.
    static func tools() -> [[String: Any]] {
        func tool(_ name: String, _ desc: String, _ props: [String: Any], required: [String] = []) -> [String: Any] {
            ["type": "function", "function": [
                "name": name, "description": desc,
                "parameters": ["type": "object", "properties": props, "required": required]]]
        }
        let item: [String: Any] = ["type": "string", "description": "The title (or a distinctive part of it) of the target file."]
        let tag: [String: Any] = ["type": "string", "description": "A label/tag name."]
        return [
            tool("search_knowledge", "Semantic + keyword search over the user's files. Returns numbered source snippets.",
                 ["query": ["type": "string", "description": "A focused natural-language search query."]], required: ["query"]),
            tool("get_item", "Return the full extracted text and metadata of ONE file, found by title.",
                 ["item": item], required: ["item"]),
            tool("summarize_item", "Pull the ENTIRE text of one (possibly large) file and summarize it — more complete than get_item (which truncates). Use when the user asks to summarize/condense/TL;DR a specific document.",
                 ["item": item], required: ["item"]),
            tool("outline_item", "Extract the heading/section OUTLINE (table of contents) of a file — markdown headings, numbered sections, ALL-CAPS headers. Use to grasp a long document's structure before reading it.",
                 ["item": item], required: ["item"]),
            tool("document_outline", "The file's EXACT markdown heading hierarchy as an indented table of contents — instant and free (no model). Use to navigate a long markdown doc; complements outline_item (which summarizes).",
                 ["item": item], required: ["item"]),
            tool("generate_toc", "Build a clickable markdown table of contents from a file's headings — an indented list of [Heading](#anchor) links. Paste at the top of a long doc.",
                 ["item": item], required: ["item"]),
            tool("find_in_item", "Find the lines in ONE file that contain a phrase (case-insensitive) — a within-document grep with line numbers. Use for 'where does this note mention X?' (search_knowledge searches across files instead).",
                 ["item": item, "query": ["type": "string", "description": "The phrase/substring to find within the file."]],
                 required: ["item", "query"]),
            tool("read_frontmatter", "Read the YAML-style frontmatter (the leading '---' metadata block) of a note — keys like title, tags, date. Distinct from extract_key_values (which scans the whole file).",
                 ["item": item], required: ["item"]),
            tool("extract_quotes", "Pull quoted passages from a file — straight (\"…\") and smart (curly) quotes. Use to find citations or highlighted lines in a note.",
                 ["item": item], required: ["item"]),
            tool("extract_ips", "Pull valid IPv4 addresses from a file (logs, configs) — each octet validated 0–255. Use for log analysis.",
                 ["item": item], required: ["item"]),
            tool("extract_domains", "Pull the unique domain names from a file — hosts from URLs and domains from email addresses. Use to see which sites appear in a note.",
                 ["item": item], required: ["item"]),
            tool("extract_times", "Pull times of day from a file — '3:30 PM', '09:00', '12pm'. Validated hours/minutes. Use to find schedule/meeting times.",
                 ["item": item], required: ["item"]),
            tool("extract_percentages", "Pull percentage values from a file ('45%', '12.5 %') and summarize them — count plus average, min, and max. Use for stats/report notes.",
                 ["item": item], required: ["item"]),
            tool("keyword_extract", "Surface a file's most salient TERMS by frequency (a quick topical fingerprint) — useful to suggest labels or grasp what a document is about at a glance.",
                 ["item": item], required: ["item"]),
            tool("extract_links", "Pull all the web LINKS (http/https URLs) out of a file — for collecting references or following sources.",
                 ["item": item], required: ["item"]),
            tool("extract_dates", "Pull all DATES (ISO, slashed, or month-name) out of a file — for finding deadlines or events, e.g. to set reminders.",
                 ["item": item], required: ["item"]),
            tool("timeline", "List the dates in a file in CHRONOLOGICAL order (earliest first) — build a timeline of a contract, project log, or history. Unlike extract_dates (document order).",
                 ["item": item], required: ["item"]),
            tool("extract_emails", "Pull all EMAIL addresses out of a file — for collecting contacts.",
                 ["item": item], required: ["item"]),
            tool("extract_phone_numbers", "Pull all PHONE NUMBERS out of a file (international, US-parens, or separated forms) — for collecting contacts, alongside extract_emails.",
                 ["item": item], required: ["item"]),
            tool("extract_contacts", "One-call CONTACTS roll-up for a file: the people, emails, and phone numbers found, grouped together. Use for 'who do I contact in this file' instead of calling entity_extract + extract_emails + extract_phone_numbers separately.",
                 ["item": item], required: ["item"]),
            tool("extract_action_items", "Pull actionable TASKS / TODOs / commitments out of a file — checkbox items, TODO/FIXME/ACTION markers, and 'need to / must / follow up / remember to' phrasing. Use to turn notes into follow-ups (then optionally add_reminder for each).",
                 ["item": item], required: ["item"]),
            tool("extract_figures", "Pull monetary AMOUNTS ($1,234.56, 50 USD, €10) and PERCENTAGES (15%) out of a file — for invoices, contracts, budgets, reports ('what amounts are in this file').",
                 ["item": item], required: ["item"]),
            tool("extract_questions", "Pull the QUESTIONS out of a file — turn a document into an FAQ, study deck, or interview-prep list ('what questions does this raise/ask').",
                 ["item": item], required: ["item"]),
            tool("extract_acronyms", "Pull the ACRONYMS / initialisms out of a file (API, HTTP, TCP…) and their spelled-out expansions when present — build a glossary or decode jargon.",
                 ["item": item], required: ["item"]),
            tool("extract_code_blocks", "Pull the fenced CODE SNIPPETS (```lang … ```) out of a file, with their language — 'show me the code in this doc', build a snippet library.",
                 ["item": item], required: ["item"]),
            tool("extract_tables", "Pull markdown TABLES out of a file as parsed rows — a doc's densest structured data (specs, schedules, pricing, comparisons). Returns each table's dimensions, headers, and preview rows.",
                 ["item": item], required: ["item"]),
            tool("inspect_csv", "Parse a CSV or TSV file (spreadsheet/export) into columns and rows — auto-detects the delimiter, handles quoted fields with embedded commas/newlines. Reports the column names, row count, and sample rows.",
                 ["item": item], required: ["item"]),
            tool("csv_to_table", "Render a CSV/TSV file as a clean aligned MARKDOWN table for display in the chat (first N rows). Use when the user wants to SEE a spreadsheet, not just its stats.",
                 ["item": item], required: ["item"]),
            tool("csv_sort", "Sort a CSV/TSV file by a column and show the result as a table. Set numeric=true to sort by number, descending=true to reverse. Call inspect_csv first to see the column names.",
                 ["item": item, "column": ["type": "string", "description": "The column header to sort by (case-insensitive)."],
                  "numeric": ["type": "boolean", "description": "Sort by numeric value (default false)."],
                  "descending": ["type": "boolean", "description": "Reverse order (default false)."]],
                 required: ["item", "column"]),
            tool("csv_select", "Pick and reorder columns from a CSV/TSV file (like SQL SELECT col1, col3) and show the result as a table. Use to narrow a wide spreadsheet to the columns you care about.",
                 ["item": item, "columns": ["type": "string", "description": "Comma-separated column names, in the order you want, e.g. 'name, city'."]],
                 required: ["item", "columns"]),
            tool("csv_group_by", "Group a CSV/TSV by a column and aggregate another — like SQL GROUP BY. op is count (default), sum, mean, min, or max; 'aggregate' is required for everything except count. E.g. group_by=region, aggregate=sales, op=sum.",
                 ["item": item,
                  "group_by": ["type": "string", "description": "Column to group rows by."],
                  "aggregate": ["type": "string", "description": "Numeric column to aggregate (not needed for count)."],
                  "op": ["type": "string", "enum": ["count", "sum", "mean", "min", "max"], "description": "Aggregation (default count)."]],
                 required: ["item", "group_by"]),
            tool("csv_dedupe", "Remove duplicate rows from a CSV/TSV — exact whole-row duplicates by default, or keep the first row per 'by' column. Reports how many were removed and shows the result.",
                 ["item": item, "by": ["type": "string", "description": "Optional column to dedupe by (keeps first per value). Omit for exact whole-row dedupe."]],
                 required: ["item"]),
            tool("csv_transpose", "Transpose a CSV/TSV — swap rows and columns so each column becomes a row. Useful for flipping a small table. Shows the result.",
                 ["item": item], required: ["item"]),
            tool("csv_distinct", "List the unique values in a CSV/TSV column (SQL SELECT DISTINCT) — explore what's in a column. Call inspect_csv first to see the column names.",
                 ["item": item, "column": ["type": "string", "description": "The column header (case-insensitive)."]],
                 required: ["item", "column"]),
            tool("csv_types", "Infer the type of each CSV/TSV column — number, boolean, date, text, or empty — by sampling its values. A quick schema view.",
                 ["item": item], required: ["item"]),
            tool("csv_to_json", "Convert a CSV/TSV file into a JSON array of objects (header row → keys; values stay strings). Use to reshape a spreadsheet for an API or further processing.",
                 ["item": item], required: ["item"]),
            tool("csv_column_stats", "Compute aggregate statistics for ONE column of a CSV/TSV file — numeric sum/mean/min/max when the column is numeric, otherwise the most frequent values. Use to answer 'total revenue?', 'most common status?'. Call inspect_csv first to see the column names.",
                 ["item": item, "column": ["type": "string", "description": "The exact column header to analyze (case-insensitive)."]],
                 required: ["item", "column"]),
            tool("csv_filter", "Select the rows of a CSV/TSV file that match a predicate — e.g. 'status = open', 'amount >= 500', 'name contains da'. Operators: = != > < >= <= contains (numeric when both sides are numbers, else case-insensitive text). Returns the matching rows.",
                 ["item": item, "where": ["type": "string", "description": "A predicate like 'column OP value', e.g. 'amount >= 500' or 'status = open'."]],
                 required: ["item", "where"]),
            tool("inspect_json", "Describe the SHAPE/schema of a JSON file (config, API export, log) — top-level type, keys with their value types, array lengths, and nesting. Use to understand an export's structure before reasoning about it.",
                 ["item": item], required: ["item"]),
            tool("json_value", "Extract the value at a path from a JSON file — dot/bracket syntax like 'address.city', 'items[0].id', or '[2]'. Scalars are returned literally; objects/arrays as compact JSON. Call inspect_json first to see the structure.",
                 ["item": item, "path": ["type": "string", "description": "A dot/bracket path, e.g. 'user.name' or 'results[0].score'."]],
                 required: ["item", "path"]),
            tool("json_to_table", "Render a JSON file as an aligned MARKDOWN table — best for an array of objects (a column per key), also handles a single object (key/value) or an array of scalars. Use when the user wants to SEE a JSON export.",
                 ["item": item], required: ["item"]),
            tool("json_to_csv", "Convert a JSON file (array of objects, or a single object) into CSV — proper RFC-4180 quoting. Use to export a JSON response for a spreadsheet.",
                 ["item": item], required: ["item"]),
            tool("json_keys", "List every unique key PATH in a JSON file — 'user.name', 'items[].id' — a flat view of the structure. Pair with json_value to read a path.",
                 ["item": item], required: ["item"]),
            tool("json_pluck", "From a JSON file that's an ARRAY of objects, pull one field from every object — e.g. all 'email' values. Returns the list of values.",
                 ["item": item, "key": ["type": "string", "description": "The object key to pluck from each array element."]],
                 required: ["item", "key"]),
            tool("json_flatten", "Flatten a nested JSON file into dotted 'path = value' lines (a.b, x[0]) — a flat, scannable view of every value.",
                 ["item": item], required: ["item"]),
            tool("json_filter", "Filter a JSON file that's an ARRAY of objects by a predicate — e.g. 'status = active', 'score >= 80'. Operators: = != > < >= <= contains. Shows the matching rows as a table.",
                 ["item": item, "where": ["type": "string", "description": "A predicate like 'key OP value', e.g. 'score >= 80'."]],
                 required: ["item", "where"]),
            tool("text_stats", "Readability + length metrics for a file — word/sentence counts, estimated reading time, and a Flesch Reading Ease score with a plain-language band. Use to answer 'how long is this?' or 'how hard is it to read?'.",
                 ["item": item], required: ["item"]),
            tool("task_progress", "Measure a markdown CHECKLIST's completion in a file — counts done vs pending boxes ([x] vs [ ]) and a percent-complete. Unlike extract_action_items (only open TODOs), this reports the whole list including finished items.",
                 ["item": item], required: ["item"]),
            tool("quick_summary", "An INSTANT extractive summary of a file — picks its most salient existing sentences by word-frequency, no AI model (works offline, no API key). Faster/cheaper than summarize_item; use it for a quick gist or when the model is unavailable.",
                 ["item": item], required: ["item"]),
            tool("extract_key_values", "Pull 'Key: Value' METADATA pairs from a file — note headers / front-matter like 'Status: Done', 'Due: Friday', 'Owner: Sam'. Excludes times and URLs. Use to read a note's structured fields.",
                 ["item": item], required: ["item"]),
            tool("redact_pii", "Produce a SHAREABLE copy of a file with personal identifiers masked — emails, phone numbers, and US SSNs become [email]/[phone]/[ssn]. Reports what was redacted. Use before exporting or quoting a note externally.",
                 ["item": item], required: ["item"]),
            tool("scan_secrets", "Scan a file for leaked CREDENTIALS — API keys (AWS/Google), access tokens (GitHub/Slack), PEM private keys, and password/token assignments. Reports findings with the secret MASKED. Use to check a config or code paste before sharing.",
                 ["item": item], required: ["item"]),
            tool("key_phrases", "Extract the recurring multi-word KEY PHRASES (topics) from a file — e.g. 'machine learning', 'quarterly report'. A richer topical fingerprint than keyword_extract (single words). Use to grasp or label what a document is about.",
                 ["item": item], required: ["item"]),
            tool("extract_amounts", "Pull MONETARY amounts from a file (receipts, invoices, expense notes) — $1,200.50, €30, 45 USD — and total them per currency. Use to answer 'how much in total?' or list the charges in a document.",
                 ["item": item], required: ["item"]),
            tool("extract_definitions", "Pull DEFINITION sentences from a file ('X means Y', 'HTTP stands for…', 'a vector is an…') to build a glossary. Offline and pure (define_term does a single model lookup instead).",
                 ["item": item], required: ["item"]),
            tool("extract_mentions", "Pull #hashtags and @mentions from a file with their counts — note tags and people. Correctly ignores email addresses and markdown headings.",
                 ["item": item], required: ["item"]),
            tool("parse_url", "Break a URL into its parts — scheme, host, path, decoded query parameters, and fragment. Use to inspect what a link (e.g. a tracking URL) actually contains.",
                 ["url": ["type": "string", "description": "The URL to parse, e.g. 'https://example.com/p?utm_source=x'."]],
                 required: ["url"]),
            tool("jwt_decode", "Decode a JSON Web Token's header and payload (claims like issuer, subject, expiry, scopes) — base64url, no key needed. Does NOT verify the signature (that requires the secret); it's an inspector, not a validator.",
                 ["token": ["type": "string", "description": "The JWT (header.payload.signature)."]],
                 required: ["token"]),
            tool("slugify", "Turn a string into a URL/filename-safe slug — 'My Great Note!' → 'my-great-note'. Folds accents to ASCII and collapses punctuation. Use for anchors, filenames, or artifact names.",
                 ["text": ["type": "string", "description": "The text to slugify, e.g. a title."]],
                 required: ["text"]),
            tool("hash_text", "Compute the SHA-256 fingerprint of some text — for checksums, deduplication, or checking whether two pieces of text are identical. Returns the full hex hash and a short 8-char fingerprint.",
                 ["text": ["type": "string", "description": "The text to hash."]],
                 required: ["text"]),
            tool("base64", "Base64-encode or -decode text. Set mode to 'encode' (default) or 'decode'. Use for data URIs, tokens, or decoding an encoded snippet.",
                 ["text": ["type": "string", "description": "The text to encode, or the base64 to decode."],
                  "mode": ["type": "string", "enum": ["encode", "decode"], "description": "encode (default) or decode."]],
                 required: ["text"]),
            tool("html_entities", "Escape or unescape HTML entities (< ↔ &lt;, & ↔ &amp;, etc.). Set mode to 'escape' (default) to make text HTML-safe, or 'unescape' to decode.",
                 ["text": ["type": "string", "description": "The text to escape or unescape."],
                  "mode": ["type": "string", "enum": ["escape", "unescape"], "description": "escape (default) or unescape."]],
                 required: ["text"]),
            tool("url_encode", "Percent-encode or -decode text for URLs/query strings. Set mode to 'encode' (default) or 'decode'. E.g. 'hello world' → 'hello%20world'.",
                 ["text": ["type": "string", "description": "The text to encode, or the percent-encoded text to decode."],
                  "mode": ["type": "string", "enum": ["encode", "decode"], "description": "encode (default) or decode."]],
                 required: ["text"]),
            tool("caesar", "Caesar-cipher (ROT-N) a string — shift each letter by 'shift' positions (default 13 = ROT13). Case and non-letters preserved. ROT13 decodes itself.",
                 ["text": ["type": "string", "description": "The text to shift."],
                  "shift": ["type": "integer", "description": "Letters to shift (default 13). Negative to decode a forward shift."]],
                 required: ["text"]),
            tool("nato", "Spell text using the NATO phonetic alphabet (Alfa, Bravo, Charlie…) — read out a code, name, or confirmation number unambiguously over the phone. Digits and punctuation handled too.",
                 ["text": ["type": "string", "description": "The text to spell out phonetically."]],
                 required: ["text"]),
            tool("morse", "Encode text to International Morse code or decode Morse back to text. Letters separated by spaces, words by ' / '. Auto-detects direction; set 'mode' to 'encode'/'decode' to force it.",
                 ["text": ["type": "string", "description": "Plain text to encode, or dot/dash Morse to decode."],
                  "mode": ["type": "string", "description": "'encode', 'decode', or omit to auto-detect."]],
                 required: ["text"]),
            tool("vigenere", "Vigenère cipher — encode or decode text with a keyword (a stronger classic cipher than Caesar). Case preserved, non-letters pass through. Set 'mode' to 'encode' (default) or 'decode'.",
                 ["text": ["type": "string", "description": "The text to encode or decode."],
                  "key": ["type": "string", "description": "The keyword (letters only are used)."],
                  "mode": ["type": "string", "description": "'encode' (default) or 'decode'."]],
                 required: ["text", "key"]),
            tool("char_frequency", "Letter-frequency analysis of text — counts each A–Z letter (case-insensitive) with percentages, sorted most→least common. The classic first step in breaking a substitution/Caesar cipher. Set 'top' to cap rows.",
                 ["text": ["type": "string", "description": "The text to analyze."],
                  "top": ["type": "integer", "description": "Max letters to show (default 26)."]],
                 required: ["text"]),
            tool("make_checklist", "Turn a list of items into a markdown checklist (- [ ] item). Pass items one per line; existing bullets/numbers are stripped and a leading [x] is kept as done. Use to convert notes or action items into a task list.",
                 ["data": ["type": "string", "description": "Items, one per line, e.g. 'buy milk\\ncall Sam'."]],
                 required: ["data"]),
            tool("format_list", "Reformat a list of items — style 'numbered', 'bullet', 'comma', or 'and' (Oxford-comma sentence). Existing bullets/numbers are stripped first.",
                 ["text": ["type": "string", "description": "Items, one per line."],
                  "style": ["type": "string", "enum": ["numbered", "bullet", "comma", "and"], "description": "Output style."]],
                 required: ["text", "style"]),
            tool("change_case", "Convert text case — set mode to 'upper', 'lower', 'title', or 'sentence'. Use to clean up or normalize a heading or pasted text.",
                 ["text": ["type": "string", "description": "The text to convert."],
                  "mode": ["type": "string", "enum": ["upper", "lower", "title", "sentence"], "description": "Target case."]],
                 required: ["text", "mode"]),
            tool("headline_case", "Title-case a headline AP/Chicago-style — major words capitalized, short articles/conjunctions/prepositions lowercased (unless first or last). E.g. 'the lord of the rings' → 'The Lord of the Rings'.",
                 ["text": ["type": "string", "description": "The headline/title to format."]],
                 required: ["text"]),
            tool("acronym", "Make an acronym from a phrase — first letter of each word, uppercased. E.g. 'Portable Document Format' → 'PDF'. Set skip_minor=true to drop words like 'the', 'of'.",
                 ["phrase": ["type": "string", "description": "The phrase to acronymize."],
                  "skip_minor": ["type": "boolean", "description": "Skip minor words (the, of, and…). Default false."]],
                 required: ["phrase"]),
            tool("case_style", "Convert an identifier between styles — 'snake' (snake_case), 'camel' (camelCase), 'kebab' (kebab-case), or 'pascal' (PascalCase). Auto-detects the input's words.",
                 ["text": ["type": "string", "description": "The identifier/phrase to convert."],
                  "style": ["type": "string", "enum": ["snake", "camel", "kebab", "pascal"], "description": "Target style."]],
                 required: ["text", "style"]),
            tool("word_frequency", "Count the most frequent content words in some text (stopwords filtered) — a quick topical fingerprint. Set 'top' to cap how many to return (default 10).",
                 ["text": ["type": "string", "description": "The text to analyze."],
                  "top": ["type": "integer", "description": "How many top words to return (default 10)."]],
                 required: ["text"]),
            tool("count_text", "Count characters (with/without spaces), words, lines, and sentences of some text. Quick stats on a pasted passage.",
                 ["text": ["type": "string", "description": "The text to measure."]],
                 required: ["text"]),
            tool("unicode_info", "Inspect the Unicode code point (U+XXXX) and official name of each character in some text — useful for invisible characters, look-alikes, emoji, or accents.",
                 ["text": ["type": "string", "description": "The text whose characters to inspect."]],
                 required: ["text"]),
            tool("count_occurrences", "Count how many times a word or phrase appears in some text. Case-insensitive by default; set case_sensitive=true or whole_word=true to refine. Overlapping matches aren't double-counted.",
                 ["text": ["type": "string", "description": "The text to search."],
                  "needle": ["type": "string", "description": "The word/phrase to count."],
                  "case_sensitive": ["type": "boolean", "description": "Match case exactly (default false)."],
                  "whole_word": ["type": "boolean", "description": "Only count whole-word matches (default false)."]],
                 required: ["text", "needle"]),
            tool("palindrome", "Check whether text reads the same forwards and backwards (ignoring case and punctuation). E.g. 'A man, a plan, a canal: Panama'.",
                 ["text": ["type": "string", "description": "The text to check."]],
                 required: ["text"]),
            tool("anagram", "Check whether two phrases are anagrams — same letters rearranged (case, spaces, and punctuation ignored). E.g. 'Listen' / 'Silent'.",
                 ["a": ["type": "string", "description": "First phrase."],
                  "b": ["type": "string", "description": "Second phrase."]],
                 required: ["a", "b"]),
            tool("reverse", "Reverse text. mode 'chars' (default) reverses the characters; mode 'words' reverses the word order.",
                 ["text": ["type": "string", "description": "The text to reverse."],
                  "mode": ["type": "string", "enum": ["chars", "words"], "description": "chars (default) or words."]],
                 required: ["text"]),
            tool("truncate", "Shorten text to a length with an ellipsis. mode 'chars' (default) limits characters; mode 'words' limits words. Ellipsis added only if cut.",
                 ["text": ["type": "string", "description": "The text to truncate."],
                  "length": ["type": "integer", "description": "Max characters (or words)."],
                  "mode": ["type": "string", "enum": ["chars", "words"], "description": "chars (default) or words."]],
                 required: ["text", "length"]),
            tool("replace_text", "Find and replace text within a string — replaces every occurrence of 'find' with 'replace' and reports the count. Set case_insensitive to true to ignore case.",
                 ["text": ["type": "string", "description": "The text to transform."],
                  "find": ["type": "string", "description": "The substring to find."],
                  "replace": ["type": "string", "description": "The replacement (may be empty to delete)."],
                  "case_insensitive": ["type": "boolean", "description": "Ignore case when matching (default false)."]],
                 required: ["text", "find", "replace"]),
            tool("extract_between", "Extract every span of text between a start and end marker — e.g. between '<b>' and '</b>', or '[' and ']'. Use to pull fields out of templated or markup text.",
                 ["text": ["type": "string", "description": "The text to scan."],
                  "start": ["type": "string", "description": "The opening marker."],
                  "end": ["type": "string", "description": "The closing marker."]],
                 required: ["text", "start", "end"]),
            tool("word_diff", "Compare two texts at the WORD level — which words were added vs removed (case-insensitive). Complements the line-level diff tools.",
                 ["a": ["type": "string", "description": "The first text."],
                  "b": ["type": "string", "description": "The second text."]],
                 required: ["a", "b"]),
            tool("line_diff", "Line-level diff between two text blocks — a unified-style view (unchanged ' ', removed '-', added '+') using LCS matching. Use to compare two versions of a note, config, or list.",
                 ["a": ["type": "string", "description": "The original text (one item per line)."],
                  "b": ["type": "string", "description": "The new text to compare against A."]],
                 required: ["a", "b"]),
            tool("extract_fields", "Pull named fields out of free text into a structured table — e.g. extract 'name, date, amount, vendor' from a receipt or email. Uses DeepSeek's force-JSON mode for reliable structure. Missing fields show as —.",
                 ["text": ["type": "string", "description": "The source text to extract from."],
                  "fields": ["type": "string", "description": "Field names to extract, comma-separated (e.g. 'name, date, total')."]],
                 required: ["text", "fields"]),
            tool("fill_in", "Fill in the gap between a prefix and a suffix — generate the missing middle (DeepSeek fill-in-the-middle). Great for completing a function body, a paragraph, or a config block between two anchors.",
                 ["prefix": ["type": "string", "description": "The text/code BEFORE the gap."],
                  "suffix": ["type": "string", "description": "The text/code AFTER the gap (optional)."]],
                 required: ["prefix"]),
            tool("deep_reason", "Answer a HARD analytical question with DeepSeek's reasoner model (R1) — it thinks step-by-step before answering. Use for proofs, multi-step logic, trade-off analysis, debugging, or anything needing careful reasoning (not quick lookups). Returns the answer plus its reasoning.",
                 ["question": ["type": "string", "description": "The analytical question to reason through."]],
                 required: ["question"]),
            tool("confidence_check", "Answer a question AND report how confident the model is (from its token log-probabilities) — high/moderate/low with a percentage. Use when the user wants a reliability signal, e.g. 'how sure are you that…'.",
                 ["question": ["type": "string", "description": "The question to answer with a confidence score."]],
                 required: ["question"]),
            tool("text_similarity", "Measure how similar two texts are — a Jaccard word-overlap ratio (0–100%). Use to gauge how alike two notes/passages are.",
                 ["a": ["type": "string", "description": "The first text."],
                  "b": ["type": "string", "description": "The second text."]],
                 required: ["a", "b"]),
            tool("edit_distance", "Levenshtein edit distance between two strings — the minimum single-character edits to turn one into the other, plus a similarity %. Good for typos / fuzzy matching.",
                 ["a": ["type": "string", "description": "The first string."],
                  "b": ["type": "string", "description": "The second string."]],
                 required: ["a", "b"]),
            tool("reindent", "Indent or dedent a block of text. mode 'indent' adds 'spaces' leading spaces to each line; mode 'dedent' strips the common leading whitespace. Handy for code snippets.",
                 ["text": ["type": "string", "description": "The text to reindent."],
                  "mode": ["type": "string", "enum": ["indent", "dedent"], "description": "indent or dedent."],
                  "spaces": ["type": "integer", "description": "Spaces to add for 'indent' (default 2)."]],
                 required: ["text", "mode"]),
            tool("wrap_text", "Word-wrap text to a column width (default 80), preserving blank-line paragraph breaks. Use to reflow prose or comments.",
                 ["text": ["type": "string", "description": "The text to wrap."],
                  "width": ["type": "integer", "description": "Column width (default 80)."]],
                 required: ["text"]),
            tool("extract_json", "Pull valid JSON object(s) or array(s) embedded in a larger text — JSON buried in logs, model output, or prose. Returns each JSON block found.",
                 ["text": ["type": "string", "description": "The text that may contain JSON."]],
                 required: ["text"]),
            tool("format_json", "Pretty-print or minify a JSON string. Set mode to 'pretty' (default, indented + sorted keys) or 'minify' (compact). Returns an error if the JSON is invalid.",
                 ["json": ["type": "string", "description": "The JSON text to format."],
                  "mode": ["type": "string", "enum": ["pretty", "minify"], "description": "pretty (default) or minify."]],
                 required: ["json"]),
            tool("json_merge", "Merge two JSON objects — the second wins on conflicts. Deep by default (recurses into nested objects); set deep=false for a top-level-only merge. Use to combine configs/settings.",
                 ["a": ["type": "string", "description": "Base JSON object."],
                  "b": ["type": "string", "description": "JSON object to merge in (wins on conflicts)."],
                  "deep": ["type": "boolean", "description": "Recurse into nested objects (default true)."]],
                 required: ["a", "b"]),
            tool("sort_lines", "Sort the lines of a block of text — alphabetical by default. Set numeric=true to sort by number, descending=true to reverse, unique=true to drop duplicates. Blank lines are removed.",
                 ["text": ["type": "string", "description": "The lines to sort (one per line)."],
                  "numeric": ["type": "boolean", "description": "Sort by numeric value (default false)."],
                  "descending": ["type": "boolean", "description": "Reverse order (default false)."],
                  "unique": ["type": "boolean", "description": "Remove duplicate lines (default false)."]],
                 required: ["text"]),
            tool("compare_lists", "Set operations between two newline-separated lists — mode 'common' (in both), 'only_a' (in A not B), 'only_b' (in B not A), or 'union' (all). Use to compare two sets of names/tags/values.",
                 ["a": ["type": "string", "description": "List A, one item per line."],
                  "b": ["type": "string", "description": "List B, one item per line."],
                  "mode": ["type": "string", "enum": ["common", "only_a", "only_b", "union"], "description": "The set operation (default common)."]],
                 required: ["a", "b"]),
            tool("strip_markdown", "Strip markdown formatting from text to get plain prose — removes headings, bold/italic, links, images, inline code, bullets, and quotes. Use to get a clean text version.",
                 ["text": ["type": "string", "description": "The markdown text to strip."]],
                 required: ["text"]),
            tool("number_bases", "Show an integer in decimal, hex, binary, and octal. Input may be decimal or prefixed (0x.., 0b.., 0o..). E.g. '255' or '0xff'.",
                 ["value": ["type": "string", "description": "The integer, decimal or 0x/0b/0o-prefixed."]],
                 required: ["value"]),
            tool("convert_base", "Convert an integer between any numeric bases 2–36 — e.g. value=FF, from=16, to=10 → 255.",
                 ["value": ["type": "string", "description": "The number, in base 'from'."],
                  "from": ["type": "integer", "description": "Source base (2–36)."],
                  "to": ["type": "integer", "description": "Target base (2–36)."]],
                 required: ["value", "from", "to"]),
            tool("number_to_words", "Spell an integer in English words — e.g. 1234 → 'one thousand two hundred thirty-four'. Handles zero and negatives, up to trillions.",
                 ["value": ["type": "string", "description": "The integer to spell out."]],
                 required: ["value"]),
            tool("number_format", "Add thousands separators to a number — '1234567' → '1,234,567'. Keeps sign and decimals.",
                 ["value": ["type": "string", "description": "The number to format."]],
                 required: ["value"]),
            tool("ordinal", "Format a number as an ordinal — 1 → 1st, 23 → 23rd, 111 → 111th (handles the 11/12/13 exceptions).",
                 ["value": ["type": "string", "description": "The integer to make ordinal."]],
                 required: ["value"]),
            tool("gcd_lcm", "Compute the greatest common divisor and least common multiple of two integers. E.g. a=12, b=18 → gcd 6, lcm 36.",
                 ["a": ["type": "integer", "description": "First integer."],
                  "b": ["type": "integer", "description": "Second integer."]],
                 required: ["a", "b"]),
            tool("factorize", "Tell whether a number is prime, or give its prime factorization — e.g. 60 → 2 × 2 × 3 × 5.",
                 ["value": ["type": "integer", "description": "The integer to factorize (2 … 1e12)."]],
                 required: ["value"]),
            tool("temperature", "Convert a temperature between Celsius, Fahrenheit, and Kelvin. E.g. value=100, from=C, to=F → 212.",
                 ["value": ["type": "number", "description": "The temperature value."],
                  "from": ["type": "string", "description": "Source unit: C, F, or K."],
                  "to": ["type": "string", "description": "Target unit: C, F, or K."]],
                 required: ["value", "from", "to"]),
            tool("color", "Convert a color between hex and RGB — '#FF5733' → rgb(255, 87, 51), or '255,87,51' → #FF5733. Supports shorthand like #fff.",
                 ["value": ["type": "string", "description": "A hex color (#RRGGBB or #RGB) or 'r,g,b'."]],
                 required: ["value"]),
            tool("luhn", "Check whether a number passes the Luhn checksum (used by credit-card numbers, IMEIs, and many IDs). Spaces and dashes are ignored.",
                 ["value": ["type": "string", "description": "The number to validate."]],
                 required: ["value"]),
            tool("password_strength", "Estimate a password's strength on-device — entropy in bits plus a label (very weak…very strong), based on length and the character classes used. Never sent anywhere.",
                 ["password": ["type": "string", "description": "The password to evaluate."]],
                 required: ["password"]),
            tool("validate_email", "Check whether a string is a well-formed email address (local@domain.tld). Distinct from extract_emails, which finds them in text.",
                 ["email": ["type": "string", "description": "The email address to validate."]],
                 required: ["email"]),
            tool("percentage", "Everyday percentage math. mode 'of' → a% of b; 'what_percent' → a is what % of b; 'change' → percent change from a to b. E.g. mode=of, a=10, b=200.",
                 ["mode": ["type": "string", "enum": ["of", "what_percent", "change"], "description": "Which calculation."],
                  "a": ["type": "number", "description": "First number."],
                  "b": ["type": "number", "description": "Second number."]],
                 required: ["mode", "a", "b"]),
            tool("compound_interest", "Compound-interest future value — what a principal grows to at a given annual rate over some years. Set 'principal', 'rate' (annual %), 'years', and optional 'times_per_year' (compounding frequency, default 1).",
                 ["principal": ["type": "number", "description": "Starting amount."],
                  "rate": ["type": "number", "description": "Annual interest rate, as a percent (e.g. 5 for 5%)."],
                  "years": ["type": "number", "description": "Number of years."],
                  "times_per_year": ["type": "integer", "description": "Compounding periods per year (default 1; 12=monthly)."]],
                 required: ["principal", "rate", "years"]),
            tool("loan_payment", "Monthly payment on a fixed-rate loan (amortization) — e.g. a mortgage or car loan. Set 'principal', 'rate' (annual %), and 'years'. Reports the monthly payment and total interest.",
                 ["principal": ["type": "number", "description": "Loan amount."],
                  "rate": ["type": "number", "description": "Annual interest rate, as a percent (e.g. 6 for 6%)."],
                  "years": ["type": "number", "description": "Loan term in years."]],
                 required: ["principal", "rate", "years"]),
            tool("tip", "Calculate a tip and split a bill — tip amount, grand total, and per-person share. Set 'bill', 'percent' (e.g. 20), and optional 'people' (default 1).",
                 ["bill": ["type": "number", "description": "The pre-tip bill amount."],
                  "percent": ["type": "number", "description": "Tip percentage, e.g. 18."],
                  "people": ["type": "integer", "description": "Split among this many people (default 1)."]],
                 required: ["bill", "percent"]),
            tool("roman_numeral", "Convert between Arabic and Roman numerals (1–3999), direction auto-detected. E.g. '1994' → MCMXCIV, or 'IV' → 4.",
                 ["value": ["type": "string", "description": "A number (1–3999) or a Roman numeral."]],
                 required: ["value"]),
            tool("duration", "Convert between seconds and human-readable durations. A plain number is read as seconds → '1h 1m 1s'; a duration like '1h 30m' or '1:30:00' → seconds.",
                 ["value": ["type": "string", "description": "Seconds (e.g. '3661') or a duration ('1h 30m', '1:30:00')."]],
                 required: ["value"]),
            tool("file_size", "Convert between a byte count and a human-readable size (decimal, like Finder). A plain number of bytes → '1.5 MB'; a size like '1.5 MB' or '2GB' → bytes.",
                 ["value": ["type": "string", "description": "Bytes (e.g. '1500000') or a size ('1.5 MB', '2GB')."]],
                 required: ["value"]),
            tool("weekday", "What day of the week a date falls on (YYYY-MM-DD) — e.g. '2026-06-22' → Monday. Pure calendar math; works for any past or future date.",
                 ["date": ["type": "string", "description": "A date in YYYY-MM-DD form."]],
                 required: ["date"]),
            tool("date_diff", "Count the days between two dates (YYYY-MM-DD). Omit 'to' to count from 'from' until today — e.g. 'how many days until 2026-12-25?'.",
                 ["from": ["type": "string", "description": "Start date, YYYY-MM-DD."],
                  "to": ["type": "string", "description": "End date, YYYY-MM-DD. Defaults to today if omitted."]],
                 required: ["from"]),
            tool("add_days", "Compute the date a number of days from a given date (YYYY-MM-DD) — negative goes backward. Returns the resulting date and its weekday. E.g. 'what's the date 30 days after 2026-06-15?'.",
                 ["date": ["type": "string", "description": "Start date, YYYY-MM-DD."],
                  "days": ["type": "integer", "description": "Days to add (negative to subtract)."]],
                 required: ["date", "days"]),
            tool("bar_chart", "Render a horizontal ASCII bar chart to VISUALIZE numbers in the chat — pass 'label: value' pairs (comma- or newline-separated), e.g. 'Jan: 8, Feb: 5, Mar: 3'. Great for showing column stats, trends, or tallies you computed.",
                 ["data": ["type": "string", "description": "Label:value pairs, comma- or newline-separated, e.g. 'Q1: 12, Q2: 19'. Plain numbers only (no thousands separators)."]],
                 required: ["data"]),
            tool("make_table", "Format rows into a clean aligned MARKDOWN table — pass newline-separated rows, cells pipe- or comma-separated, first row = header. Use to present a list or result tidily in the chat.",
                 ["data": ["type": "string", "description": "Newline-separated rows; cells comma- or pipe-separated. First row is the header. E.g. 'Name, Age\\nAda, 36'."]],
                 required: ["data"]),
            tool("number_stats", "Descriptive statistics over a list of numbers you provide — count, sum, mean, median, min, max, range, and standard deviation. Pass values separated by commas or spaces, e.g. '12, 19, 7, 23'.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines, e.g. '12 19 7 23'."]],
                 required: ["data"]),
            tool("sparkline", "Render a compact one-line trend (▁▂▃▄▅▆▇█) from a number series — a glanceable inline trend (e.g. activity over time). Pass values separated by commas or spaces.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines, e.g. '3 5 4 8 6 9'."]],
                 required: ["data"]),
            tool("quartiles", "Compute the quartiles of a list of numbers — Q1, median, Q3, and the interquartile range (IQR). Pass values separated by commas or spaces.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines."]],
                 required: ["data"]),
            tool("percentile", "Compute the Nth percentile of a list of numbers (linear interpolation, like NumPy) — e.g. the 95th percentile of latencies. Set 'p' (0–100, default 50 = median). Pass values separated by commas or spaces.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines."],
                  "p": ["type": "string", "description": "Percentile 0–100 (default 50)."]],
                 required: ["data"]),
            tool("z_score", "Compute the z-score of a value against a list of numbers — how many standard deviations from the mean (population σ). Pass 'value' to score one number, or omit it to standardize the whole list. Values separated by commas/spaces.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines."],
                  "value": ["type": "string", "description": "A single number to score (optional; omit to standardize the list)."]],
                 required: ["data"]),
            tool("histogram", "Render a text histogram of a number list — buckets the values into bins and shows the distribution. Set 'bins' (default 10). Pass values separated by commas or spaces.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines."],
                  "bins": ["type": "integer", "description": "Number of bins (default 10)."]],
                 required: ["data"]),
            tool("outliers", "Detect outliers in a list of numbers using Tukey's IQR fences — flags values far below Q1 or above Q3. Set 'k' (default 1.5; use 3 for extreme-only). Needs at least 4 values. Pass values separated by commas or spaces.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines."],
                  "k": ["type": "string", "description": "Fence multiplier (default 1.5; 3 = extreme outliers only)."]],
                 required: ["data"]),
            tool("correlation", "Pearson correlation coefficient (r, −1…1) between two equal-length number lists — how strongly two series move together. Pass 'x' and 'y' as numbers separated by commas or spaces.",
                 ["x": ["type": "string", "description": "First series, numbers separated by commas/spaces/newlines."],
                  "y": ["type": "string", "description": "Second series, same length as x."]],
                 required: ["x", "y"]),
            tool("moving_average", "Smooth a number series with a simple moving average (rolling mean) over a window — reveals the trend. Set 'window' (default 3). Returns one value per window position. Pass values separated by commas or spaces.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines."],
                  "window": ["type": "integer", "description": "Window size (default 3)."]],
                 required: ["data"]),
            tool("pct_change", "Period-over-period percentage change of a number series — how each value compares to the previous one (e.g. month-over-month growth). Returns n−1 values; a step after a zero is n/a. Pass values separated by commas or spaces.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines."]],
                 required: ["data"]),
            tool("running_total", "Cumulative (running) totals of a number series — each value is the sum so far; the last is the grand total. Great for finances/progress. Pass values separated by commas or spaces.",
                 ["data": ["type": "string", "description": "Numbers separated by commas/spaces/newlines."]],
                 required: ["data"]),
            tool("tally", "Count how often each distinct value appears in a list (a GROUP BY) — statuses, tags, names. Pass values one per line (or comma-separated). Returns a frequency table; pair with bar_chart to visualize it.",
                 ["data": ["type": "string", "description": "Values one per line or comma-separated, e.g. 'open\\nopen\\nclosed'."]],
                 required: ["data"]),
            tool("entity_extract", "Pull the NAMED ENTITIES (people, organizations, places) mentioned in a file — answer 'who/what is mentioned here', build contact or topic lists. On-device, offline.",
                 ["item": item], required: ["item"]),
            tool("sentiment", "Gauge the emotional TONE of a file (how positive/negative) — useful for reviews, feedback, or journal entries. Returns a label and a −1…+1 score. On-device, offline.",
                 ["item": item], required: ["item"]),
            tool("detect_language", "Detect what LANGUAGE a file is written in (with confidence) — useful before translating, or to triage a multilingual library. On-device, offline.",
                 ["item": item], required: ["item"]),
            tool("reading_time", "Estimate how long a file takes to read — word count and minutes (~220 wpm).",
                 ["item": item], required: ["item"]),
            tool("readability", "Score how DENSE / approachable a file is — Flesch reading-ease (0 hard … 100 easy) with a grade band. Pairs with reading_time to triage a quick skim vs. a slog. English-oriented; on-device.",
                 ["item": item], required: ["item"]),
            tool("suggest_labels", "Propose 3-5 LABELS for a file from its salient terms, reusing existing library labels where they fit. Previews by default; pass apply=true to actually add them.",
                 ["item": item, "apply": ["type": "boolean", "description": "Set true to ADD the suggested labels. Omit/false = preview only."]],
                 required: ["item"]),
            tool("suggest_tags_from_neighbors", "Propose LABELS for a file from what its most SIMILAR files are already tagged (a collaborative signal) — complements suggest_labels (which uses the file's own terms). Best for tagging a new file consistently with the rest of the library. Preview; apply with add_tag.",
                 ["item": item], required: ["item"]),
            tool("auto_label_untagged", "BATCH organize: find untagged files and propose labels for EACH from its content (reusing existing labels). Previews by default; pass apply=true to label them all.",
                 ["limit": ["type": "integer", "description": "Max files to process (default 10)."],
                  "apply": ["type": "boolean", "description": "Set true to APPLY labels to all proposed files. Omit/false = preview."]]),
            tool("list_tags", "List every label/tag in the knowledge base with the number of items carrying each.", [:]),
            tool("save_search", "SAVE a search query under a name so it can be re-run later — e.g. save 'unpaid invoices' as 'invoices'. Use when the user says 'save this search' or 'remember this query'.",
                 ["name": ["type": "string", "description": "A short name for the saved search."],
                  "query": ["type": "string", "description": "The search query to save."]],
                 required: ["name", "query"]),
            tool("list_saved_searches", "List the user's saved searches (their names and queries).", [:]),
            tool("search_conversations", "Search the user's PAST CONVERSATIONS (chat titles and messages) — 'did we talk about X before', 'find that chat about Y'. Returns matching threads with dates.",
                 ["query": ["type": "string", "description": "What to look for across past chats."]],
                 required: ["query"]),
            tool("run_saved_search", "Run a previously SAVED search by its name and return the matching files (cited).",
                 ["search": ["type": "string", "description": "Name (or part) of the saved search to run."]],
                 required: ["search"]),
            tool("delete_saved_search", "Delete a saved search by its name.",
                 ["search": ["type": "string", "description": "Name (or part) of the saved search to delete."]],
                 required: ["search"]),
            tool("tag_stats", "Label ANALYTICS: per-label usage counts AND which labels frequently appear together (co-occurrence). Use to understand how the library is organized or to spot related topics.", [:]),
            tool("find_by_tag", "List the files that carry a given label/tag.", ["tag": tag], required: ["tag"]),
            tool("summarize_tag", "Summarize ALL files carrying a label into ONE cohesive overview, with citations. Use for 'summarize my <label> notes'.",
                 ["tag": tag], required: ["tag"]),
            tool("library_stats", "Totals (items, chunks) and a breakdown of the knowledge base by file kind.", [:]),
            tool("most_cited", "List the files you REFERENCE MOST in conversations (by how often they've been cited) — your go-to / most-relied-upon sources.",
                 ["limit": ["type": "integer", "description": "How many to list (default 5)."]]),
            tool("activity_trend", "Summarize file ACTIVITY over the last N days — total changes, the busiest day, and recent pace. Use for 'how active have I been', 'when did I add the most'.",
                 ["days": ["type": "integer", "description": "Window in days (default 30)."]]),
            tool("summarize_library", "A one-call DIGEST of the whole knowledge base — totals, kind breakdown, top labels, untagged count, and the newest files. Use for 'what's in my library / give me an overview' or before suggesting what to do next.", [:]),
            tool("library_health", "A one-call HEALTH CHECK — label coverage, untagged count, near-duplicate labels — with concrete cleanup recommendations (auto_label_untagged, merge_tags). Use for 'how organized is my library / what should I clean up'.", [:]),
            tool("find_duplicates", "Find sets of files with IDENTICAL content (exact duplicates) — useful before deleting redundant items.", [:]),
            tool("find_similar_titles", "Find sets of files with NEAR-DUPLICATE names (versioned or copied — e.g. 'Report final.pdf' vs 'Report final v2.pdf', 'notes (1).txt') even when their content differs. Library hygiene; complements find_duplicates (which needs identical content).", [:]),
            tool("library_themes", "Surface the DOMINANT TOPICS across the whole library (terms appearing in many files) — for 'what are the main themes in my knowledge' or to suggest what to explore.", [:]),
            tool("library_languages", "Break down the WHOLE library by LANGUAGE — what share of files are English vs Chinese vs … — for a multilingual collection. On-device detection.",
                 ["limit": ["type": "integer", "description": "Max files to sample (default 300)."]]),
            tool("catch_me_up", "A proactive BRIEFING: what changed recently, which reminders are due/overdue, and any tidy-up nudges — answer 'catch me up', 'what's new', 'what should I look at'.",
                 ["days": ["type": "integer", "description": "Look-back/look-ahead window in days (default 7)."]]),
            tool("find_by_kind", "List files of a given KIND/type — pdf, image, markdown, text, code, webpage, email, word.",
                 ["kind": ["type": "string", "description": "e.g. 'pdf', 'image', 'markdown'."]], required: ["kind"]),
            tool("add_tag", "Add a label to a file.", ["item": item, "tag": tag], required: ["item", "tag"]),
            tool("remove_tag", "Remove a label from a file.", ["item": item, "tag": tag], required: ["item", "tag"]),
            tool("rename_tag", "Rename a label everywhere it is used.",
                 ["from": ["type": "string", "description": "Existing label name."],
                  "to": ["type": "string", "description": "New label name."]], required: ["from", "to"]),
            tool("delete_tag", "Delete a label ENTIRELY — remove it from every file that has it (the label disappears from the library).",
                 ["tag": tag], required: ["tag"]),
            tool("merge_tags", "Consolidate several messy/duplicate labels into ONE (e.g. 'ml, machine-learning, ML' → 'machine learning'). Bulk + safe: requires confirm=true; without it, previews how many files are affected.",
                 ["from": ["type": "string", "description": "Comma-separated source labels to merge (e.g. 'ml, machine-learning')."],
                  "into": ["type": "string", "description": "The single target label they all become."],
                  "confirm": ["type": "boolean", "description": "Must be true to apply. Omit/false = preview the affected count."]],
                 required: ["from", "into"]),
            tool("recent_items", "List the most recently added/modified files.",
                 ["limit": ["type": "integer", "description": "How many to list (default 10)."]]),
            tool("largest_items", "List the BIGGEST files by size (storage triage) — useful for finding bulky items.",
                 ["limit": ["type": "integer", "description": "How many to list (default 10)."]]),
            tool("oldest_items", "List the OLDEST files (least recently added/modified) — for finding stale content to review.",
                 ["limit": ["type": "integer", "description": "How many to list (default 10)."]]),
            tool("recent_changes", "List files changed/added within a TIME WINDOW — the last N days (default 7) or since a given date. Use for 'what changed this week', 'what's new since June 1'.",
                 ["days": ["type": "integer", "description": "Look-back window in days (default 7). Ignored if 'since' is set."],
                  "since": ["type": "string", "description": "Optional ISO date (YYYY-MM-DD) to count changes from."]]),
            tool("find_by_date", "List files whose date falls in an explicit RANGE — e.g. 'what did I save between March 1 and May 31', 'files created in 2025'. Either bound may be omitted for an open-ended range.",
                 ["start": ["type": "string", "description": "Start ISO date (YYYY-MM-DD), inclusive. Omit for no lower bound."],
                  "end": ["type": "string", "description": "End ISO date (YYYY-MM-DD), inclusive (whole day). Omit for no upper bound."],
                  "field": ["type": "string", "description": "Which date to filter on: 'modified' (default) or 'created'."],
                  "limit": ["type": "integer", "description": "Max files to list (default 25)."]]),
            tool("related_items", "Find files semantically related to a given file.", ["item": item], required: ["item"]),
            tool("suggest_connections", "AUTONOMOUS suggestion: for a file, surface semantically-related files that share NO label with it — content you could connect but haven't yet. Offer to co-tag them. Great for 'what should I link to this'.",
                 ["item": item], required: ["item"]),
            tool("reveal_in_finder", "Reveal a file in macOS Finder (opens Finder, selects the file).", ["item": item], required: ["item"]),
            tool("open_file", "Open a file with its default macOS application.", ["item": item], required: ["item"]),
            tool("delete_item", "Remove a file from the knowledge base ONLY (the file on disk is untouched). DESTRUCTIVE: requires the EXACT title AND confirm=true. Call once WITHOUT confirm to preview; only call with confirm=true after the user agrees.",
                 ["item": item, "confirm": ["type": "boolean", "description": "Must be true to actually delete. Omit or false = preview only."]], required: ["item"]),
            tool("untagged_items", "List files that have no labels yet (useful for tidying up).",
                 ["limit": ["type": "integer", "description": "How many to list (default 20)."]]),
            tool("tag_search_results", "Add a label to EVERY file matching a search query (bulk). Requires confirm=true; without it, previews the matches first.",
                 ["query": ["type": "string", "description": "Search query selecting the files to label."],
                  "tag": tag,
                  "confirm": ["type": "boolean", "description": "Must be true to apply. Omit/false = preview the matched files."]],
                 required: ["query", "tag"]),
            tool("batch_tag", "Add ONE label to SEVERAL specific files named by title, in one confirmed action — e.g. to co-tag the files from suggest_connections. Requires confirm=true; without it, previews which titles resolve (and flags any missing/ambiguous).",
                 ["items": ["type": "string", "description": "Comma-separated file titles to label."],
                  "tag": tag,
                  "confirm": ["type": "boolean", "description": "Must be true to apply. Omit/false = preview which files would be labelled."]],
                 required: ["items", "tag"]),
            tool("reingest", "Re-read a file from disk and re-index it (use after the file changed on disk).",
                 ["item": item], required: ["item"]),
            tool("web_search", "Search the OPEN WEB for current information not in the user's files. Returns numbered web sources you can cite. Use it for recent events, definitions, or to augment local knowledge.",
                 ["query": ["type": "string", "description": "A focused web search query."]], required: ["query"]),
            tool("web_research", "DEEP web research in ONE call: searches the web, then fetches and reads the FULL text of the top sources in parallel, returning a combined corpus to synthesize a grounded, cited answer. Prefer this over web_search+fetch_url when you need depth (how/why questions, comparisons, current state of a topic).",
                 ["query": ["type": "string", "description": "The research question or topic."],
                  "depth": ["type": "integer", "description": "How many sources to read in full (1-5, default 3)."]],
                 required: ["query"]),
            tool("define_term", "Quickly DEFINE/look up a term — checks the user's OWN library first, and only falls back to the web if it isn't found locally. Use for 'what is X', 'define X', glossary lookups.",
                 ["term": ["type": "string", "description": "The term or concept to define."]], required: ["term"]),
            tool("create_artifact", "Produce ANY non-trivial DELIVERABLE by writing and running code in a sandbox: a document, PDF, book, report, data analysis, chart/visualization, slide deck, web page, or mini-app — grounded in the user's knowledge base. This is the right tool for ANY 'write / make / build / generate / create / 写 / 做 / 生成 …' request that yields a file or long-form output, ESPECIALLY large multi-step ones (e.g. 'write a book and generate a PDF'). Do NOT try to assemble such deliverables with the read-only retrieval tools. Saves files to ~/Documents/Mnemosyne Artifacts and reveals them. Pass `revise` (an existing artifact's title) to update one in place.",
                 ["task": ["type": "string", "description": "What to build, or how to change it when revising. Include the desired output format (e.g. PDF) and any title."],
                  "revise": ["type": "string", "description": "Optional: the TITLE of an existing artifact to update in place (use after read_artifact / list_recent_artifacts)."]],
                 required: ["task"]),
            tool("fetch_url", "Fetch and READ the full text of a web page (beyond a search snippet). Use after web_search to read a promising result, or when the user gives a URL.",
                 ["url": ["type": "string", "description": "The page URL to read."]], required: ["url"]),
            tool("save_note", "Save synthesized findings BACK into the user's knowledge base as a searchable note (a .md file in ~/Documents/Mnemosyne Notes). Use when the user asks to remember/save a summary or conclusion.",
                 ["title": ["type": "string", "description": "Short note title."],
                  "content": ["type": "string", "description": "The note body (markdown)."]],
                 required: ["title", "content"]),
            tool("current_datetime", "Get the current local date and time. Use this whenever recency matters (e.g. 'recent', dates, scheduling, or before a time-sensitive web_search).", [:]),
            tool("calculate", "Evaluate an arithmetic EXPRESSION exactly (+ - * / % ^ and parentheses). Use this for any math instead of computing it yourself.",
                 ["expression": ["type": "string", "description": "e.g. (3+4)*2^3 - 10%3"]], required: ["expression"]),
            tool("unit_convert", "Convert a value between units of LENGTH (m, km, cm, mm, mi, yd, ft, in), MASS (g, kg, mg, t, lb, oz), or TEMPERATURE (C, F, K).",
                 ["value": ["type": "number", "description": "The numeric value to convert."],
                  "from": ["type": "string", "description": "Source unit, e.g. 'km' or 'celsius'."],
                  "to": ["type": "string", "description": "Target unit, e.g. 'mi' or 'F'."]],
                 required: ["value", "from", "to"]),
            tool("translate", "Translate text into another language. Use when the user asks to translate something.",
                 ["text": ["type": "string", "description": "The text to translate."],
                  "to": ["type": "string", "description": "Target language, e.g. 'English', '中文', 'Spanish'."]],
                 required: ["text", "to"]),
            tool("translate_item", "Translate a whole FILE's contents into another language (by title).",
                 ["item": item,
                  "to": ["type": "string", "description": "Target language, e.g. 'English', '中文'."]],
                 required: ["item", "to"]),
            tool("compare_items", "Fetch TWO files so you can compare/contrast them. Returns both as numbered sources.",
                 ["item_a": ["type": "string", "description": "Title of the first file."],
                  "item_b": ["type": "string", "description": "Title of the second file."]],
                 required: ["item_a", "item_b"]),
            tool("diff_items", "Compute a line-level DIFF/changelog between two files (e.g. two versions of a doc) — shows exactly which lines were added/removed. Use for 'what changed between X and Y'.",
                 ["item_a": ["type": "string", "description": "Title of the OLD/first file."],
                  "item_b": ["type": "string", "description": "Title of the NEW/second file."]],
                 required: ["item_a", "item_b"]),
            tool("list_recent_artifacts", "List deliverables you've already built (so you can reference or extend them).",
                 ["limit": ["type": "integer", "description": "How many to list (default 8)."]]),
            tool("read_artifact", "Read the main file of a previously-built artifact (by title) so you can revise or build on it.",
                 ["name": ["type": "string", "description": "Title (or part of it) of a past artifact."]], required: ["name"]),
            tool("export_artifact", "Export/share a built artifact as a .zip on the Desktop (so the user can send or archive it). Use when the user asks to share, export, send, or save-out a deliverable.",
                 ["name": ["type": "string", "description": "Title (or part of it) of the artifact to export."]], required: ["name"]),
            tool("open_artifact", "Open a previously-built artifact in its default app (e.g. the HTML in a browser). Use when the user asks to open/show/view a deliverable.",
                 ["name": ["type": "string", "description": "Title (or part of it) of the artifact to open."]], required: ["name"]),
            tool("add_reminder", "Set a deferred task / reminder that persists (a TODO the Ask tab can act on later). Use when the user says 'remind me to…', 'follow up on…', or you defer work for later.",
                 ["title": ["type": "string", "description": "What to be reminded of / the task."],
                  "due": ["type": "string", "description": "Optional human-readable when ('tomorrow', 'Fri', '2026-07-01')."]],
                 required: ["title"]),
            tool("pin_fact", "PIN a fact to long-term memory so you ALWAYS remember it across every conversation (it's injected into context and never compacted away) — e.g. the user's name, preferences, or an ongoing project detail.",
                 ["fact": ["type": "string", "description": "The fact to remember permanently."]], required: ["fact"]),
            tool("list_pinned_facts", "List the facts pinned to long-term memory.", [:]),
            tool("unpin_fact", "Remove a fact from long-term memory (by its text or part of it).",
                 ["fact": ["type": "string", "description": "The pinned fact (or part) to remove."]], required: ["fact"]),
            tool("list_reminders", "List the user's open (and recently completed) reminders / deferred tasks.", [:]),
            tool("due_reminders", "List open reminders that are DUE SOON or OVERDUE — those whose due date falls within the next N days — earliest first. Use for 'what's due', 'what's coming up', 'anything overdue'.",
                 ["days": ["type": "integer", "description": "Look-ahead window in days (default 7). Overdue items always included."]]),
            tool("complete_reminder", "Mark a reminder / deferred task as done (by its title or part of it).",
                 ["reminder": ["type": "string", "description": "Title (or part) of the reminder to complete."]],
                 required: ["reminder"]),
        ]
    }
}
